In [2]:
import numpy as np
# now you learn advanced numpy array joining
# stacking funciton in numpy (vstack, hstack & column_stack)
n1 = np.array([10, 20, 30])
n2 = np.array([100, 200, 300])

In [3]:
# vstack to joining two array vartically
np.vstack((n1, n2))

array([[ 10,  20,  30],
       [100, 200, 300]])

In [4]:
# hstack to joining two array horizontallay
np.hstack((n1, n2))

array([ 10,  20,  30, 100, 200, 300])

In [ ]:
# column_stack to joining two array in column wise
np.column_stack((n1, n2))

array([[ 10, 100],
       [ 20, 200],
       [ 30, 300]])

In [ ]:
n3 = np.array([10, 20, 30, 40])
n4 = np.array([40, 50, 60, 70])

In [ ]:
#common eliment presented this two numpy array using intersec1d
np.intersect1d(n3, n4)

array([40])

In [ ]:
# Uniqe eliment n3
np.setdiff1d(n3, n4)

array([10, 20, 30])

In [ ]:
# Uniqe eliment n4
np.setdiff1d(n4, n3)

array([50, 60, 70])

In [14]:
n5 = np.array([10, 40, 30, 79, 30])
n5

array([10, 40, 30, 79, 30])

In [15]:
# save the numpy array as a my_array
np.save('my_array', n5)

In [19]:
# load my_array in n2 variable
n2 = np.load('my_array.npy')
n2

array([10, 40, 30, 79, 30])