In [ ]:
import numpy as np
n1 = np.array([10, 20, 30, 40, 50, 60])
n2 = np.array([50, 60, 70, 80, 90, 100])

In [ ]:
n2

array([ 50,  60,  70,  80,  90, 100])

In [ ]:
n1

array([10, 20, 30, 40, 50, 60])

In [ ]:
# Addition to numpy array for presented full sum
np.sum([n1, n2])

660

In [ ]:
#Addition to numpy array for indevidual array
np.sum([n1, n2], axis=1)

array([210, 450])

In [ ]:
# given array to Addition numpy array for sum element index
np.sum([n1, n2], axis=0)

array([ 60,  80, 100, 120, 140, 160])

In [ ]:
# addition any number to increment all element in this array
n1+=2
n1

array([ 430,  750, 1070, 1390, 1710, 2030])

In [ ]:
# substraction any number to decrement all element in this array
n2-=5
n2

array([20, 30, 40, 50, 60, 70])

In [ ]:
# multiplication any number to multiply all element in this array
n1 = n1 * 2
n1

array([ 860, 1500, 2140, 2780, 3420, 4060])

In [ ]:
# divition any number to devided all element in this array
n2 = n2 / 2
n2

array([2.5 , 3.75, 5.  , 6.25, 7.5 , 8.75])

In [58]:
n3 = np.array([10, 20, 30, 40, 50, 60])
n4 = np.array([60, 70, 80, 90, 100, 110])

In [59]:
# mean element of this list
np.mean([n3])

35.0

In [60]:
# median element of this list
np.median([n4])

85.0

In [62]:
#Standard division
np.std(n3)

17.07825127659933