In [5]:
import numpy as np

In [ ]:
n1 = np.array([10, 20, 30, 40])
n1

array([10, 20, 30, 40])

In [ ]:
type(n1)

numpy.ndarray

In [9]:
type(n2)

numpy.ndarray

In [10]:
# initializing numpy array with zeros. 3 Colom & 5 Row
n3 = np.zeros((3, 5))
n3

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
# initializing numpy array with zeros. 2 Colom & 3 Row
n4 = np.zeros((2, 3), dtype=int)
n4

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
# intializing numpy array with same number
n5 = np.full((2, 5), 10)
n5

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [ ]:
# Initializing numby array within a range
n6 = np.arange(1, 20)
n6

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [ ]:
# Initializing numby array within a range (increament as 5)
n7 = np.arange(0, 101, 5)
n7

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

In [ ]:
# Initializing numby array with random number
# when 1st parameter to start and 2nd parameter to 2nd range for random number and 3rd parameter is mention the number of random value
n8 = np.random.randint(1, 100, 5)
n8


array([74,  2, 35, 33, 54])

In [11]:
# checking the shape of number & update
n9 = np.array([[10, 50, 30], [40, 50, 39]])
n9

array([[10, 50, 30],
       [40, 50, 39]])

In [12]:
n9.shape

(2, 3)

In [19]:
#update the shape of this array
n9.shape = (3, 2)
n9.shape

(3, 2)

In [20]:
n9

array([[10, 50],
       [30, 40],
       [50, 39]])

In [ ]:
# So today we learn with numpy function for array
# The list of today learing topics
# numpy array
# numpy array initializing with zeno, same number, number of range and random np.number
# And numpy array shape check and update